name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update packages
      run: sudo apt-get update

    - name: Install Docker
      run: |
        sudo apt-get install -y docker.io
        sudo apt-get install -y docker-compose

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd ${{ secrets.WORK_DIR }}
          git pull origin main
          docker-compose down
          docker-compose rm -f
          docker-compose up -d --build
        EOF

    - name: Clean up SSH
      run: rm -rf ~/.ssh
